services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: measurements
    ports:
      - "5432:5432"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
  
  api:
    build:
      context: .  # Diretório atual
      dockerfile: Dockerfile  # Nome do Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db  # Espera pelo serviço db
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}  # Chave de API, se necessário
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: measurements
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./:/usr/src/app  # Mapeia o diretório atual para dentro do container
